[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "cd Backend/SmartInventory.API",
  "dotnet restore",
  "dotnet publish -c Release -o out"
]

[start]
cmd = "cd Backend/SmartInventory.API/out && dotnet SmartInventory.API.dll"
