[build]
builder = "NIXPACKS"
buildCommand = "cd Backend/SmartInventory.API && dotnet restore && dotnet publish -c Release -o out"

[deploy]
startCommand = "cd Backend/SmartInventory.API/out && dotnet SmartInventory.API.dll"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
